[profile.default]
src = "src"
out = "out"
libs = ["lib"]
auto_detect_remappings = false

remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
]
gas_reports = ['WrappedDMD']
optimizer = true
optimizer_runs = 1000000
names = true
sizes = true
via_ir = true
evm_version = "london"
ffi = true
ast = true
build_info = true
extra_output_files = ["abi"]
fs_permissions = [{ access = "read", path = "./out" }]

[rpc_endpoints]
dmd_mainnet = "https://rpc.bit.diamonds"

[etherscan]
dmd_mainnet = { key = "123", url = "https://explorer.bit.diamonds/api" }
